language: python
python:
- "2.7"
- "3.4"
os: linux
env:
  - BUILD_TOOL=scons"
  - BUILD_TOOL=autotools"

matrix:
  include:
  - os: osx
    language: generic
    env: BUILD_TOOL=scons
  - os: osx
    language: generic
    env: BUILD_TOOL=autotools

# sudo is required to prevent xvfb crashes from container-based workers.
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libsdl2-dev
      - scons

before_install:
- source build/.travis/before_install.sh

install:
- source build/.travis/install.sh

before_script:
- pip install pytest pytest-cov
- (cd python && python setup.py develop)
- export UNITTEST_ARGS=""
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export UNITTEST_ARGS="~~[!nonportable]"; fi'

script:
- 'if [[ "$BUILD_TOOL" == "autotools" ]]; then echo "#include <libtcod.h>" | gcc -xc -c -I$HOME/.local/include/libtcod -; fi'
- 'if [[ "$BUILD_TOOL" == "autotools" ]]; then echo "#include <libtcod.hpp>" | gcc -xc++ -std=c++11 -c -I$HOME/.local/include/libtcod -; fi'
- 'if [[ "$BUILD_TOOL" == "autotools" ]]; then echo "#include <gui/gui.hpp>" | gcc -xc++ -std=c++11 -c -I$HOME/.local/include/libtcod -; fi'
- 'if [[ "$BUILD_TOOL" == "autotools" ]]; then (cd build/autotools && make check); fi'
- 'if [[ "$BUILD_TOOL" == "scons" ]]; then LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR ./unittest $UNITTEST_ARGS; fi'
- (cd python && pytest -v)
deploy:
  provider: releases
  api_key:
    secure: oZQmlAWgh6QPSedG1Bxp7WPnYvsr+j896MZF1BBa1FhxLyHPLCie0dDELKvY4t16NT8s8xyrfobLWEPyzQdXwKpY/OcVguKQTwDkU9VmSeHEVoxD7Wa51OQea9WcACHdzMhgzIqjSpbdVYn9t9hnNIWHbcqNSMjIwelFzZx9Pypcdrf7NQx0C5QLg7oKy7SYKDReR0GPe1TfS3D97FjqEBixe27uPdqinslCtUYv1zP5eAfivlZKEPlVAhIY7U67UVCJ+/eCMl9MoaeppV/06fIC/+ltH2au2mwTrcj9kDZdplBgcyjl6MQERv9T88ZCpgHT84cWnkLeEcu7rHMNozKQ5mOLCZplNyFFQwfn303vpXUIhDfiN5WZ/fnOfYnd4F0oJXKXXX+4LvW9HyTlMIYQ3g5Mr/6jGQv+GThFpoA0ba4Dhb+KPjt+8foLd8YqJ+1xF3ZW15x8jo4mGs9hBJPHGvEQiQ+TVDt/u7BCTIYlbYWN5B6mp22qVAFVuKL55mADZUvCpcRvHZw9vEl4XNTCqfDpi9Px1mQGDihQjsR4tpPZlp9x3gNI96itjFvTfN4froWkC3Y65ImR1BhsGz6x98z+viMIPI2nbs6KF2olMMZjw3lfetPu5nYcEmuRV8Ax516FJwq/+goV/TvS0D+g2/bDhV7aZo+dW/Cr5X4=
  file_glob: true
  file: "build/scons/libtcod-*.tar.gz"
  skip_cleanup: true
  on:
    repo: libtcod/libtcod
    tags: true
